### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Ryan4253** [umigv/simulation_stack#11]
**Tasks**
The docs should include the following information:
- launch file explanation and arguments
- published topics ("Interfacing with the simulation")

These things should be updated
- Updated sample images
- Split testing the project into building the project and launch file explanations / arguments
- Add packages installed using sudo apt into dependency?
- Remove ros-command not found from possible issues seeing that umarv env has that defaulted
- Move URDF basics to wiki

**Comment by hardy-ethan** [comment]
note: installation script works from scratch ros install (ros-humble-desktop and ros-humble-dev or wtv) as of c70140113dd5e9f322e9bcd11c53f22cf566bbd0
