### ISSUE TITLE
Make IGVC 2024 Course Gazebo World

### ISSUE THREAD

**Issue by Ryan4253** [umigv/simulation_stack#6]
**Is your feature request related to a problem? Please describe.**
We currently have no way to simulate a IGVC field with the current code we have. 

**Describe the solution you'd like**
Create a Gazebo World file with all the components of an IGVC field. We probably want two separate worlds - one with lane lines and one with walls so that we don't need lane line detection running to test nav planning. Once the world is created, the default world in the simulation launch file should be an empty world.

**Additional context**
Example field, stolen from UofT's 2022 design report
![image](https://github.com/umigv/simulation_stack/assets/71594512/938ff87f-2f38-443f-927b-cc9ee08820b2)

Actual field can be found here
http://www.igvc.org/IGVC2024rules.pdf

**Comment by Ryan4253** [comment]
Looks like their worlds is actually open for use. All we gotta do is figure out how to comply with Apache 2.0.
https://github.com/UTRA-ART/Caffeine/tree/master/worlds

**Comment by hardy-ethan** [comment]
Pretty sure the course is the same as that model![image](https://github.com/umigv/simulation_stack/assets/102838865/63757c29-e542-4579-916b-316c1b3aae1f)

**Comment by hardy-ethan** [comment]
> Looks like their worlds is actually open for use. All we gotta do is figure out how to comply with Apache 2.0.
> 
> https://github.com/UTRA-ART/Caffeine/tree/master/worlds

pretty easy actually, we just have to include the licenses that they 
have.

> When using the Apache license, developers must include the original copyright notice, a copy of the license text itself, and in some cases, a copy of the notice file with attribution notes and a disclosure of any significant changes made to the original code. Disclosing major code changes is a key differentiator between the Apache license and other permissive open source software licensing restrictions.
- https://snyk.io/learn/apache-license/

**Comment by Ryan4253** [comment]
Looks like you are the master here then, do you wanna work on that?
I checked the folder and it looks like theres quite a bit of meshes, might not need all of those.

**Comment by hardy-ethan** [comment]
mayhaps

**Comment by Ryan4253** [comment]
Note: when this is done make the sim.launch.py world default empty.world, and update readme accordingly, and add UTRA to credits

**Comment by hardy-ethan** [comment]
Closed by @27 57aafe209996a15905888ea69d2bf91ddb397b2a caa49bc687df1428c0839c27e2061cd771b93d66
