### ISSUE TITLE
Maintain custom Velodyne fork

### ISSUE THREAD

**Issue by Ryan4253** [umigv/simulation_stack#7]
**Is your feature request related to a problem? Please describe.**
The current [velodyne package](https://github.com/ToyotaResearchInstitute/velodyne_simulator) we use appears to no longer be maintained (last commit 4 years ago, multiple unreviewed pull requests). It has a few bugs mostly related to missing textures that pull requests fix.

**Describe the solution you'd like**
Maintain our own fork and implement the unmerged pull requests

**Comment by hardy-ethan** [comment]
can attempt this today

**Comment by hardy-ethan** [comment]
it has been forked and the lidar mesh fix has been merged into said fork. also updated this repo to use the fork. @Ryan4253 need anything else before closing?

**Comment by Ryan4253** [comment]
![image](https://github.com/umigv/simulation_stack/assets/71594512/39120d59-0857-45ed-a8fb-df5d0aa4028e)
We good
